name: greenmap
description: GreenMap - Digital Waste Bank & Reward Platform supporting SDG 12
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.2.7

  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  percent_indicator: ^4.2.3
  badges: ^3.1.2
  lottie: ^3.1.2

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # QR Code
  qr_flutter: ^4.1.0

  # Image
  image_picker: ^1.1.2

  # Storage
  shared_preferences: ^2.3.2

  # Charts
  fl_chart: ^0.68.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
